---
- name: Setup MERN stack
  hosts: localhost
  tasks:
    - name: Create docker network 
      docker_network: 
        name: mynetwork

    - name: Create Mongo Container
      docker_container:
        name: MongoDB
        image: mongo
        networks: 
          - name: mynetwork
    
    - name: Add mongo container to inventory
      add_host:
        name: MongoDB
        ansible_connection: docker
          
    - name: Create Node Container
      docker_container:
        name: Node
        image: node
        networks: 
          - name: mynetwork

    - name: Add node container to inventory
      add_host:
        name: Node
        ansible_connection: docker
        
    - name: Create React Container
      docker_container:
        name: React
        image: alpine
        networks: 
          - name: mynetwork
        ports: 
          - 2222:2222